<?php
?>

<!DOCTYPE html>
<html>
<head>
<title>Antennae</title>
<style>

.img1{
    float: left;
	 box-shadow: 10px 10px grey;
}
.img2{
    float: right;
	 box-shadow: 10px 10px grey;
}
.img3{
    float: left;
	 box-shadow: 10px 10px grey;
}
.img4{
    float: right;
	 box-shadow: 10px 10px grey;
}
body {
	background-image: url("Pic/b.jpg");
   background-color: #cccccc;
}
#wrapper{
 background-image: url("Pic/h.png");
	margin: 20px auto 20px auto;
	 width: 1000px;
    padding: 25px;
   
     border-color: black;
	 border-top-style: dotted ;
   border-right-style: solid;
    border-bottom-style: dotted;
    border-left-style: solid;
	}
center{
font-family: "Comic Sans MS", Times, serif;
	 color: White;
}
p {
    font-family: "Comic Sans MS", Times, serif;
	 color: black;
}
.previous {
    background-color: #f1f1f1;
    color: black;
	font-size:30px;
}

.next {
    background-color: black;
    color: white;
	font-size:30px;
	}
	 footer {
      background-color: #cccccc;
      padding: 15px;
      border-radius: 20px;
    }
	a:hover {
    background-color: #ddd;
    color: blue;
}
	
 
</style>
</head>
<body>

   <div class="clearfix">
   <center>
<h2>The Antennae Facts</h2>
<h5>softschools.com</h5>
<center>
<div id="wrapper" class="container">

<img class="img1" src="Gal/Al1.jpg"  width="300" height="200">
<p>The Antennae are two spiral galaxies that are interacting with each other and mingling their stars. This mixing together between the galaxies began over 3 hundred million years ago. Currently, their colliding gas clouds are bursting with new star formation. As the galaxies continue to merge, long tails of gas are pulled away from each other due to gravitational interactions. At the sites of the tails is the starburst activity.
<img class="img2" src="Gal/Al2.jpg"  width="300" height="200">
 The cores of these two galaxies will be combined in one large core in a few billion years with a black hole at its heart. An elliptical galaxy of old stars will then surround the Antennae.
Interesting The Antennae Facts:
The galaxies are in the Virgo cluster and part of the Corvus constellation.
In the future, the Milky Way and Andromeda galaxies likely will combine and look similar to the Antennae during at least one point of their interaction.
The Antennae galaxies are the closest colliding galaxies to the Milky Way galaxy.
Most spiral galaxies that combine will ultimately end up as elliptical galaxies when they combine like the Antennae. The merging of the galaxies will erase all evidence of their spiral arms.
 <img class="img3" src="Gal/Al3.jpg"  width="300" height="200">
Millions of new stars will be created during the Antennae merger, but only about ten percent of them will last longer than 10 million years.
The age of these new stars will not last longer because they will be huge blue supergiants, a type of star that quickly consumes its nuclear fuel and explodes as a supernova.
During starburst activity, any remaining massive young star clusters will become the new galaxy's globular clusters.
The globular clusters will likely originate from shockwaves, generated by the galaxies collision, compressing large, massive molecular clouds.
The Antennae galaxies are located in a group with five other galaxies.
The two colliding galaxies are about 45 million light-years away from the Milky Way galaxy, but was once thought to be about 65 million light-years away.
Before the collision of the two galaxies, one was larger than the other.
The collision of the two galaxies most likely began 900 million years ago. About 600 million years ago the two galaxies passed through each other, and then 300 million years ago the stars began to be released from both galaxies.
The ejected stars of the galaxies extend much farther away and beyond the original galaxies and results in its antenna shape.
The two colliding galaxies are catalogued as NGC 4038 and NGC 4039.

</p>
<footer>
<a href="Galaxies.php" class="previous">&laquo; Back &raquo;</a>
</footer>
</div>
</body>
</html>